[2024-02-23 04:42:17,540] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ETL_toll_data.virtualenv_python manual__2024-02-23T04:31:14.182654+00:00 [queued]>
[2024-02-23 04:42:17,551] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: ETL_toll_data.virtualenv_python manual__2024-02-23T04:31:14.182654+00:00 [queued]>
[2024-02-23 04:42:17,551] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2024-02-23 04:42:17,552] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2024-02-23 04:42:17,552] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2024-02-23 04:42:17,574] {taskinstance.py:1259} INFO - Executing <Task(PythonVirtualenvOperator): virtualenv_python> on 2024-02-23 04:31:14.182654+00:00
[2024-02-23 04:42:17,583] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ETL_toll_data', 'virtualenv_python', 'manual__2024-02-23T04:31:14.182654+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpy4cafgao', '--error-file', '/tmp/tmpenbhacef']
[2024-02-23 04:42:17,584] {standard_task_runner.py:77} INFO - Job 8: Subtask virtualenv_python
[2024-02-23 04:42:17,580] {standard_task_runner.py:52} INFO - Started process 1334 to run task
[2024-02-23 04:42:17,635] {logging_mixin.py:109} INFO - Running <TaskInstance: ETL_toll_data.virtualenv_python manual__2024-02-23T04:31:14.182654+00:00 [running]> on host 5bc013e1bfce
[2024-02-23 04:42:17,682] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=mahesh@somemail.com
AIRFLOW_CTX_DAG_OWNER=Mahesh Pathak
AIRFLOW_CTX_DAG_ID=ETL_toll_data
AIRFLOW_CTX_TASK_ID=virtualenv_python
AIRFLOW_CTX_EXECUTION_DATE=2024-02-23T04:31:14.182654+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-23T04:31:14.182654+00:00
[2024-02-23 04:42:17,684] {process_utils.py:160} INFO - Executing cmd: /usr/local/bin/python -m virtualenv /tmp/venvbjb67119
[2024-02-23 04:42:17,693] {process_utils.py:164} INFO - Output:
[2024-02-23 04:42:19,517] {process_utils.py:168} INFO - created virtual environment CPython3.6.15.final.0-64 in 1504ms
[2024-02-23 04:42:19,518] {process_utils.py:168} INFO -   creator CPython3Posix(dest=/tmp/venvbjb67119, clear=False, no_vcs_ignore=False, global=False)
[2024-02-23 04:42:19,519] {process_utils.py:168} INFO -   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-02-23 04:42:19,519] {process_utils.py:168} INFO -     added seed packages: pip==21.3.1, setuptools==58.3.0, wheel==0.37.0
[2024-02-23 04:42:19,520] {process_utils.py:168} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-02-23 04:42:19,616] {process_utils.py:160} INFO - Executing cmd: /tmp/venvbjb67119/bin/pip install colorama==0.4.0
[2024-02-23 04:42:19,644] {process_utils.py:164} INFO - Output:
[2024-02-23 04:42:23,442] {process_utils.py:168} INFO - Collecting colorama==0.4.0
[2024-02-23 04:42:23,645] {process_utils.py:168} INFO -   Downloading colorama-0.4.0-py2.py3-none-any.whl (21 kB)
[2024-02-23 04:42:24,155] {process_utils.py:168} INFO - Installing collected packages: colorama
[2024-02-23 04:42:24,292] {process_utils.py:168} INFO - Successfully installed colorama-0.4.0
[2024-02-23 04:42:26,829] {process_utils.py:160} INFO - Executing cmd: /tmp/venvbjb67119/bin/python /tmp/venvbjb67119/script.py /tmp/venvbjb67119/script.in /tmp/venvbjb67119/script.out /tmp/venvbjb67119/string_args.txt
[2024-02-23 04:42:26,852] {process_utils.py:164} INFO - Output:
[2024-02-23 04:42:27,180] {process_utils.py:168} INFO - [31msome red text
[2024-02-23 04:42:27,180] {process_utils.py:168} INFO - [42mand with a green background
[2024-02-23 04:42:27,181] {process_utils.py:168} INFO - [2mand in dim text
[2024-02-23 04:42:27,181] {process_utils.py:168} INFO - [0m
[2024-02-23 04:42:27,181] {process_utils.py:168} INFO - [2mPlease wait...
[2024-02-23 04:42:28,191] {process_utils.py:168} INFO - [2mPlease wait...
[2024-02-23 04:42:29,193] {process_utils.py:168} INFO - [2mPlease wait...
[2024-02-23 04:42:30,194] {process_utils.py:168} INFO - [2mPlease wait...
[2024-02-23 04:42:31,195] {process_utils.py:168} INFO - Finished
[2024-02-23 04:42:31,413] {python.py:175} INFO - Done. Returned value was: None
[2024-02-23 04:42:31,446] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=ETL_toll_data, task_id=virtualenv_python, execution_date=20240223T043114, start_date=20240223T044217, end_date=20240223T044231
[2024-02-23 04:42:31,500] {local_task_job.py:154} INFO - Task exited with return code 0
[2024-02-23 04:42:31,553] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
